# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stockmanager.ui'
#
# Created: Tue Nov 15 17:45:47 2011
#      by: PyQt4 UI code generator 4.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1023, 768)
        MainWindow.setCursor(QtCore.Qt.ArrowCursor)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.vboxlayout = QtGui.QVBoxLayout(self.centralwidget)
        self.vboxlayout.setObjectName(_fromUtf8("vboxlayout"))
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.tellingListWidget = QtGui.QListWidget(self.centralwidget)
        self.tellingListWidget.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.tellingListWidget.setFont(font)
        self.tellingListWidget.setAutoFillBackground(True)
        self.tellingListWidget.setAlternatingRowColors(True)
        self.tellingListWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tellingListWidget.setObjectName(_fromUtf8("tellingListWidget"))
        self.hboxlayout.addWidget(self.tellingListWidget)
        self.tellingTabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tellingTabWidget.setObjectName(_fromUtf8("tellingTabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.vboxlayout1 = QtGui.QVBoxLayout(self.tab1)
        self.vboxlayout1.setObjectName(_fromUtf8("vboxlayout1"))
        self.tableWidget1 = QtGui.QTableWidget(self.tab1)
        self.tableWidget1.setAlternatingRowColors(False)
        self.tableWidget1.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget1.setColumnCount(5)
        self.tableWidget1.setObjectName(_fromUtf8("tableWidget1"))
        self.tableWidget1.setColumnCount(5)
        self.tableWidget1.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget1.setHorizontalHeaderItem(4, item)
        self.vboxlayout1.addWidget(self.tableWidget1)
        self.tellingTabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.vboxlayout2 = QtGui.QVBoxLayout(self.tab2)
        self.vboxlayout2.setObjectName(_fromUtf8("vboxlayout2"))
        self.tableWidget2 = QtGui.QTableWidget(self.tab2)
        self.tableWidget2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget2.setColumnCount(3)
        self.tableWidget2.setObjectName(_fromUtf8("tableWidget2"))
        self.tableWidget2.setColumnCount(3)
        self.tableWidget2.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget2.setHorizontalHeaderItem(2, item)
        self.vboxlayout2.addWidget(self.tableWidget2)
        self.tellingTabWidget.addTab(self.tab2, _fromUtf8(""))
        self.hboxlayout.addWidget(self.tellingTabWidget)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName(_fromUtf8("hboxlayout1"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.markAsCountedButton = QtGui.QPushButton(self.centralwidget)
        self.markAsCountedButton.setEnabled(True)
        self.markAsCountedButton.setObjectName(_fromUtf8("markAsCountedButton"))
        self.hboxlayout1.addWidget(self.markAsCountedButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.hboxlayout1.addWidget(self.pushButton)
        self.vboxlayout.addLayout(self.hboxlayout1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuBestand = QtGui.QMenu(self.menubar)
        self.menuBestand.setObjectName(_fromUtf8("menuBestand"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionData_synchroniseren = QtGui.QAction(MainWindow)
        self.actionData_synchroniseren.setObjectName(_fromUtf8("actionData_synchroniseren"))
        self.actionAfsluiten = QtGui.QAction(MainWindow)
        self.actionAfsluiten.setObjectName(_fromUtf8("actionAfsluiten"))
        self.actionAfdrukken = QtGui.QAction(MainWindow)
        self.actionAfdrukken.setObjectName(_fromUtf8("actionAfdrukken"))
        self.actionNieuwe_telling = QtGui.QAction(MainWindow)
        self.actionNieuwe_telling.setObjectName(_fromUtf8("actionNieuwe_telling"))
        self.menuBestand.addAction(self.actionNieuwe_telling)
        self.menuBestand.addSeparator()
        self.menuBestand.addAction(self.actionAfsluiten)
        self.menubar.addAction(self.menuBestand.menuAction())

        self.retranslateUi(MainWindow)
        self.tellingTabWidget.setCurrentIndex(1)
        #QtCore.QObject.connect(self.actionAfsluiten, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.setSortingEnabled(True)
        self.tableWidget1.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Product ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Product naam", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Originele hoeveelheid", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Getelde hoeveelheid", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget1.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Datum geteld", None, QtGui.QApplication.UnicodeUTF8))
        self.tellingTabWidget.setTabText(self.tellingTabWidget.indexOf(self.tab1), QtGui.QApplication.translate("MainWindow", "Getelde producten", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget2.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Product ID", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget2.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Product naam", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget2.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Aantal in stock", None, QtGui.QApplication.UnicodeUTF8))
        self.tellingTabWidget.setTabText(self.tellingTabWidget.indexOf(self.tab2), QtGui.QApplication.translate("MainWindow", "Gemiste producten", None, QtGui.QApplication.UnicodeUTF8))
        self.markAsCountedButton.setText(QtGui.QApplication.translate("MainWindow", "Markeer als geteld", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Afdrukken", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBestand.setTitle(QtGui.QApplication.translate("MainWindow", "Bestand", None, QtGui.QApplication.UnicodeUTF8))
        self.actionData_synchroniseren.setText(QtGui.QApplication.translate("MainWindow", "Data synchroniseren", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfsluiten.setText(QtGui.QApplication.translate("MainWindow", "Afsluiten", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAfdrukken.setText(QtGui.QApplication.translate("MainWindow", "Afdrukken", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNieuwe_telling.setText(QtGui.QApplication.translate("MainWindow", "nieuwe telling", None, QtGui.QApplication.UnicodeUTF8))

